### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by northoftynelpc** [NOT-LPC/notlpc-concept#11]
If I want to add two and three column tables should I use html tags or Atomic CSS?

**Comment by northoftynelpc** [comment]
Table now created on contact page.  Will use as template for other areas.

**Comment by colindensem** [comment]
I'll convert to tachyons, mostly as the table as is isn't mobile responsive.

Tables are ok... cards might be marginally nicer on this page.

e.g.
http://tachyons.io/components/cards/profile-card/index.html

Thus on a mobile it will flow down.

**Comment by colindensem** [comment]
This is an example using cards:

![screenshot from 2017-07-25 10-04-28](https://user-images.githubusercontent.com/5096/28564873-55fb951a-7122-11e7-867f-7af7cfac3754.png)
![screenshot from 2017-07-25 10-04-10](https://user-images.githubusercontent.com/5096/28564874-55fe1146-7122-11e7-8820-54b967cc22a3.png)

**Comment by northoftynelpc** [comment]
Never heard of tachyons but learnt a lot about html tables last night :)

In this instance the cards would be best and we could add an image as in the cat card linked above.

I've copied the dark-stripe link to create a table in the About/Who We Are page as may need tables in future.  Looks OK but would be better without indent position.  Is it possible to get the envelope and phone symbols in a table the same as on the cards?

**Comment by colindensem** [comment]
REmoved the padding around table, it is the pa4 =  padding all level 4

**Comment by northoftynelpc** [comment]
Cards all working.  Table in Who we are looking good.
