### ISSUE TITLE
Email Obfuscation

### ISSUE THREAD

**Issue by colindensem** [NOT-LPC/notlpc-concept#12]
Related to #10 
https://support.cloudflare.com/hc/en-us/articles/200170016-What-is-Email-Address-Obfuscation-

**Comment by northoftynelpc** [comment]
This setting is on in Cloudflare.  Cant tell if its working as we are not pointing to github yet.

**Comment by northoftynelpc** [comment]
I've checked page sources and emails are obfuscated.
