### ISSUE TITLE
Add Contact panels to news/events

### ISSUE THREAD

**Issue by colindensem** [NOT-LPC/notlpc-concept#13]
Add a contact panel/box to the footer of events/news pages.

If the metadata for one or more contacts exists, render a panel below the content accordingly.

The diary box is an example of the outcome. Render below diary box.

**Comment by colindensem** [comment]
config.toml now has a new block of config.

```

[params.contacts]
    [params.contacts.DefaultContact]
      #Required for each!
      name  = "North Of Tyne LPC"
      email = "info@northoftynelpc.com"
      phone = "0123456789"
      #Optional
      linkedin = ""
      twitter = "NOT_LPC"
      facebook= "NoTLPC"

    [params.contacts.StephenBlackman]
      #Required for each!
      name  = "Stephen Blackman"
      email = "sblackman@northoftynelpc.com"
      phone = "0123456789"
      #Optional
      linkedin = "sablackman"
      twitter = "NOT_LPC"
      facebook= "NoTLPC"

```

Define a new contact using this format, repeat `[params.contacts.NewPerson]` etc

In the content meta, if no contact is set, the DefaultContact will be used. 

To set; for example StephenBlackman as the contact, set a meta top like this:

```
---
date: 2017-06-16T12:54:06-04:00
description: "Newcastle Area Meeting"
title: "Newcastle Area Meeting"
categories: ["Events"]
contact: "stephenblackman"
---
```

The key is to be downcase in the meta, despite the CamelCase in the config.

github isn't implemented, facebook, twitter, linked in are.

**Comment by colindensem** [comment]
@northoftynelpc see the event/news pages. I didn't add the top call out on news, it looked wrong. But it can be added. Let me know.

**Comment by northoftynelpc** [comment]
All looks good.
