### ISSUE TITLE
Add mailchimp newsletter signup form

### ISSUE THREAD

**Issue by colindensem** [NOT-LPC/notlpc-concept#14]
Add the mailchimp newsletter form as a part of the footer for inclusion on every page.

**Comment by colindensem** [comment]
Template: 
`

 
<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="//northoftynelpc.us3.list-manage.com/subscribe/post?u=310b8c606711c91df50f7527c&amp;id=0492b77e96" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
<h2>Subscribe to our mailing list</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
<label for="mce-FNAME">First Name </label>
<input type="text" value="" name="FNAME" class="" id="mce-FNAME">
</div>
<div class="mc-field-group">
<label for="mce-LNAME">Last Name </label>
<input type="text" value="" name="LNAME" class="" id="mce-LNAME">
</div>
<div class="mc-field-group">
<label for="mce-MMERGE3">Organisation </label>
<input type="text" value="" name="MMERGE3" class="" id="mce-MMERGE3">
</div>
<div class="mc-field-group input-group">
    <strong>Organisation Type </strong>
    <ul><li><input type="radio" value="Community Pharmacy" name="MMERGE6" id="mce-MMERGE6-0"><label for="mce-MMERGE6-0">Community Pharmacy</label></li>
<li><input type="radio" value="Pharmacy Body / LPC" name="MMERGE6" id="mce-MMERGE6-1"><label for="mce-MMERGE6-1">Pharmacy Body / LPC</label></li>
<li><input type="radio" value="Pharmaceutical Company" name="MMERGE6" id="mce-MMERGE6-2"><label for="mce-MMERGE6-2">Pharmaceutical Company</label></li>
<li><input type="radio" value="Commissioner" name="MMERGE6" id="mce-MMERGE6-3"><label for="mce-MMERGE6-3">Commissioner</label></li>
<li><input type="radio" value="Hospital / Healthcare" name="MMERGE6" id="mce-MMERGE6-4"><label for="mce-MMERGE6-4">Hospital / Healthcare</label></li>
<li><input type="radio" value="Media / Press" name="MMERGE6" id="mce-MMERGE6-5"><label for="mce-MMERGE6-5">Media / Press</label></li>
<li><input type="radio" value="Patient / Patient Representative" name="MMERGE6" id="mce-MMERGE6-6"><label for="mce-MMERGE6-6">Patient / Patient Representative</label></li>
<li><input type="radio" value="Other" name="MMERGE6" id="mce-MMERGE6-7"><label for="mce-MMERGE6-7">Other</label></li>
</ul>
</div>
<div class="mc-field-group">
<label for="mce-MMERGE7">Job Title </label>
<input type="text" value="" name="MMERGE7" class="" id="mce-MMERGE7">
</div>
<div class="mc-field-group input-group">
    <strong>Job Role </strong>
    <ul><li><input type="radio" value="Community Pharmacy Owner" name="MMERGE4" id="mce-MMERGE4-0"><label for="mce-MMERGE4-0">Community Pharmacy Owner</label></li>
<li><input type="radio" value="Superintendent Pharmacist" name="MMERGE4" id="mce-MMERGE4-1"><label for="mce-MMERGE4-1">Superintendent Pharmacist</label></li>
<li><input type="radio" value="Community Pharmacist" name="MMERGE4" id="mce-MMERGE4-2"><label for="mce-MMERGE4-2">Community Pharmacist</label></li>
<li><input type="radio" value="Community Pharmacy Manager / Area Manager" name="MMERGE4" id="mce-MMERGE4-3"><label for="mce-MMERGE4-3">Community Pharmacy Manager / Area Manager</label></li>
<li><input type="radio" value="Community Pharmacy Team Member" name="MMERGE4" id="mce-MMERGE4-4"><label for="mce-MMERGE4-4">Community Pharmacy Team Member</label></li>
<li><input type="radio" value="Locum Community Pharmacist" name="MMERGE4" id="mce-MMERGE4-5"><label for="mce-MMERGE4-5">Locum Community Pharmacist</label></li>
<li><input type="radio" value="Other Pharmacist" name="MMERGE4" id="mce-MMERGE4-6"><label for="mce-MMERGE4-6">Other Pharmacist</label></li>
<li><input type="radio" value="LPC Officer" name="MMERGE4" id="mce-MMERGE4-7"><label for="mce-MMERGE4-7">LPC Officer</label></li>
<li><input type="radio" value="NHS Management" name="MMERGE4" id="mce-MMERGE4-8"><label for="mce-MMERGE4-8">NHS Management</label></li>
<li><input type="radio" value="Pharmaceutical Representative" name="MMERGE4" id="mce-MMERGE4-9"><label for="mce-MMERGE4-9">Pharmaceutical Representative</label></li>
<li><input type="radio" value="Academia" name="MMERGE4" id="mce-MMERGE4-10"><label for="mce-MMERGE4-10">Academia</label></li>
<li><input type="radio" value="Other" name="MMERGE4" id="mce-MMERGE4-11"><label for="mce-MMERGE4-11">Other</label></li>
</ul>
</div>
<div class="mc-field-group input-group">
    <strong>Which area are you interested in? </strong>
    <ul><li><input type="checkbox" value="1" name="group[14965][1]" id="mce-group[14965]-14965-0"><label for="mce-group[14965]-14965-0">Northumberland</label></li>
<li><input type="checkbox" value="2" name="group[14965][2]" id="mce-group[14965]-14965-1"><label for="mce-group[14965]-14965-1">Newcastle</label></li>
<li><input type="checkbox" value="4" name="group[14965][4]" id="mce-group[14965]-14965-2"><label for="mce-group[14965]-14965-2">North Tyneside</label></li>
<li><input type="checkbox" value="8" name="group[14965][8]" id="mce-group[14965]-14965-3"><label for="mce-group[14965]-14965-3">North East</label></li>
</ul>
</div>
<div class="mc-field-group input-group">
    <strong>Email Format </strong>
    <ul><li><input type="radio" value="html" name="EMAILTYPE" id="mce-EMAILTYPE-0"><label for="mce-EMAILTYPE-0">html</label></li>
<li><input type="radio" value="text" name="EMAILTYPE" id="mce-EMAILTYPE-1"><label for="mce-EMAILTYPE-1">text</label></li>
</ul>
</div>
<div id="mce-responses" class="clear">
<div class="response" id="mce-error-response" style="display:none"></div>
<div class="response" id="mce-success-response" style="display:none"></div>
</div>    
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_310b8c606711c91df50f7527c_0492b77e96" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='MMERGE3';ftypes[3]='text';fnames[6]='MMERGE6';ftypes[6]='radio';fnames[7]='MMERGE7';ftypes[7]='text';fnames[4]='MMERGE4';ftypes[4]='radio';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
`

**Comment by northoftynelpc** [comment]
Mailchimp footer tested and working.  Looks good.  Only comment is that padding below could be reduced to make a narrower ribbon.
