### ISSUE TITLE
Committing changes

### ISSUE THREAD

**Issue by northoftynelpc** [NOT-LPC/notlpc-concept#19]
Hi Colin,

Changes to 20170906-agm.md and 20170906-awards.md will not commit.  I can't see any errors so not sure why.

**Comment by colindensem** [comment]
Hi,

Looking at the build status, see reade in project root, it shows some
failing builds.

If you click the build wrecker  picture it takes you to a list of builds.

If you view, click on the red build bar, the failed one.

Scroll down the long black text output. Near the bottom you will see warn,
info and error messages.

The error one is the key.

It's time format, it needs seconds.

18:00:00

That should do it.

Colin.
