### ISSUE TITLE
Define Footer details

### ISSUE THREAD

**Issue by colindensem** [NOT-LPC/notlpc-concept#4]
The footer held in this:
https://github.com/NOT-LPC/notlpc-concept/blob/master/themes/notlpc-theme/layouts/partials/site-footer.html

Needs to have the link blocks defined.

RHS might be considered for a slim contact details as discussed on phone.

**Comment by colindensem** [comment]
@northoftynelpc This look ok now?

**Comment by northoftynelpc** [comment]
Footer looks good.
