### ISSUE TITLE
Footer Image

### ISSUE THREAD

**Issue by northoftynelpc** [NOT-LPC/notlpc-concept#8]
Tried to change footer image to webfootlogo.svg but not displaying correctly.  Guess you need to edit svg file.

**Comment by colindensem** [comment]
The header of the SVG now looks like this:
`<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:xlink="http://www.w3.org/1999/xlink"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   id="svg2"
   version="1.1"
   inkscape:version="0.92.1 r15371"
   width="{{.width}}"
   height="{{.height}}"`

So remove the XML <svg should be the start of the file, and you need to alter width and height to use variables as shown above.

**Comment by northoftynelpc** [comment]
Hi Colin,



There was a hidden transparent block in the svg which didnt show on white but does show on left edge in current footer.  I've deleted the element and edited the svg file so the attached should look correct if replaces the current file.  


Kind Wishes

 

Stephen Blackman

Chief Officer, North of Tyne Local Pharmaceutical Committee

M  |  07976132006

E  |  stephen.blackman@northoftynelpc.com

 

Please note that I only work three days a week for NoT LPC. 

My normal working days are Tuesdays, Wednesdays and Thursdays.








---- On Mon, 24 Jul 2017 17:22:54 +0100 Colin Densem &lt;notifications@github.com&gt; wrote ----




The header of the SVG now looks like this:

 &lt;svg xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:cc="http://creativecommons.org/ns#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" id="svg2" version="1.1" inkscape:version="0.92.1 r15371" width="{{.width}}" height="{{.height}}"


So remove the XML &lt;svg should be the start of the file, and you need to alter width and height to use variables as shown above.

**Comment by northoftynelpc** [comment]
Logo now displaying correctly but not centred above facebook & twitter and text below.

**Comment by colindensem** [comment]
It is centred. Whats throwing it out slightly is the SVG logo has dead space on it's right.

See screenshot.
![screenshot from 2017-07-24 18-17-14](https://user-images.githubusercontent.com/5096/28535491-7e165160-709c-11e7-8790-65f1ec42bc48.png)

We could line twitter and facebook to the right of the logo on top of each other.

**Comment by colindensem** [comment]
Added another fix to remove that space... sorry took two glances this time. Should be ok now!

**Comment by northoftynelpc** [comment]
Thanks Colin.  I was busy trying to see what was wrong with the image but it looked good in design software.  I've now added a border to the image to give some padding between it and the social icons.

Off topic but resources now compiles from resources tag not fundamentals

**Comment by colindensem** [comment]
@northoftynelpc this looks ok now?

**Comment by northoftynelpc** [comment]
Yes.  Happy with footer image.
